[GLOBAL]
pants_version = "2.0.0.dev6+git6c90064f"
pantsd = true
dynamic_ui = true
backend_packages = [
  "pants.backend.codegen.protobuf.python",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.typecheck.mypy",
]
plugins = [
]

[source]
root_patterns = [
  "/src/proto",
  "/src/py",
]

[python-setup]
interpreter_constraints = [">=3.7"]

[black]
version = "black==19.10b0"
config = "pyproject.toml"

[isort]
version = "isort[pyproject]==4.3.21"
config = "pyproject.toml"

[mypy]
version = "mypy==0.782"
config = "mypy.ini"

[protoc]
runtime_targets = [
  "//third_party/py:google",
  "//third_party/py:grpcio",
  "//third_party/py:protobuf",
]
